### ISSUE TITLE
Unable to start worker

### ISSUE THREAD

**Issue by nvijayap** [groupme/pace#9]
I see this while trying to start worker ...

> > worker = Pace::Worker.new("normal")
> > TypeError: can't convert Symbol into String
> >     from /Library/Ruby/Gems/1.8/gems/pace-0.0.6/lib/pace/worker.rb:7:in `delete'
> >     from /Library/Ruby/Gems/1.8/gems/pace-0.0.6/lib/pace/worker.rb:7:in`initialize'
> >     from (irb):5:in `new'
> >     from (irb):5

**Comment by nvijayap** [comment]
Showing above in code block now ...

<code>

> > worker = Pace::Worker.new("normal")
> > TypeError: can't convert Symbol into String
> >     from /Library/Ruby/Gems/1.8/gems/pace-0.0.6/lib/pace/worker.rb:7:in `delete'
> >     from /Library/Ruby/Gems/1.8/gems/pace-0.0.6/lib/pace/worker.rb:7:in`initialize'
> >     from (irb):5:in `new'
> >     from (irb):5
> > </code>

**Comment by nvijayap** [comment]
Resolved thus ...

worker = Pace::Worker.new(:queue=>"normal")

The README.md at https://github.com/groupme/pace needs to be updated.

**Comment by jpignata** [comment]
Sorry about that. We'll fix the README.
